# Generated by Django 4.0.3 on 2022-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_training', '0002_alter_picture_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='studied',
            field=models.BooleanField(default='False'),
        ),
    ]
